* 将 Win10 的配色改为护眼色
电脑默认的颜色为白色，刺眼，看时间长后容易疲劳，而绿色和黑色比较护眼。
** 通过个性化更改
将个性化-颜色，改为暗色，这样win10的配色就会变成黑色的。

不过这个暗色的对比度有点高，有些刺眼，我们可以通过通过调低显示器的对比度进行弥补。

** 通过软件设置修改
win10 的深色模式对软件的适配不是很好，我们可以通过修改软件设置中的配色，修改为深色模式。
** 浏览器修改
上边虽然把大部分软件都修改为了深色模式，但是却无法对浏览器浏览的内容进行修改，这时就要用到浏览器的插件。

我用的是Firefox，下面以Firefox为例。

ps: 我原本也想把浏览器的内容改成深色模式的，可是用了一段时间发现，对部分网站的适配并不好，因为大部分网站在设计的时候只考虑可浅色模式，好多图片也是为了适应浅色模式的，插件改不了图片的颜色，导致有些图片在深色背景下显示效果不好，于是我就用了另外一种护眼的颜色。
*** 安装主题
我用的是 Solarized Taiji，这种配色在vscode,hdbuilder里面都有，据说是很护眼的。
*** 安装插件
Dark Reader占用资源太多，有明显的卡顿，我就没用，我用的是 Dark Background and Light Text。
然后在global设置中将配色改为 Solarized 的颜色，我参考了 vscode 和 Hdbuilder.
| Option                     | color   |
|----------------------------+---------|
| Default foreground color   | #154431 |
| Default background color   | #fdf6e3 |
| Default link color         | #154431 |
| Default visited link color | #7b6931 |
| Default active link color  | #e8dfc4 |
| Default selection color    | #bcd68d |

由于插件对于duckduckgo的效果不是很好，所以我就对duckduckgo进行了单独的设置。
duckduckgo 在设置里面是可以自定义颜色的。
先将duckduckgo的主题设置为普通，
然后将 背景颜色改为：#f1ead8，搜索栏颜色改为：#e9e2cf。
其他的颜色等看不顺眼再改。
** End
至此，就改完了，这下看电脑舒服多了。
** 2020-8-1 更新
现在我已经不用护眼模式了，因为无论哪个护眼模式的插件都不能很好地兼容所有网站，而且容易造成网页加载缓慢。
